
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 11 23:07:01 COT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Seleciona = 2;
  public static final int Id = 9;
  public static final int Menor = 8;
  public static final int ERROR = 12;
  public static final int EOF = 0;
  public static final int Desde = 3;
  public static final int Todo = 5;
  public static final int error = 1;
  public static final int Mayor = 7;
  public static final int DatoTabla = 10;
  public static final int Igual = 6;
  public static final int Numero = 11;
  public static final int Donde = 4;
}

